### PR TITLE
Conwaydev webpack

### PR DESCRIPTION
**Pull request by DarthHater**
Couple fixes I needed to make to get Docker back up and running. 

Let me know if this is ok by you @conwaydev , and we can merge it.

By the way this is hilarious: 

screen shot 2017-11-28 at 10 26 26 am

This supercedes #1

### CODE REVIEW

**Comment by DarthHater** [comment]
Another thing I hadn't fully picked up on until looking deeper is you moved from Typescript to ES6 basically. Any reason?

**Comment by conwaydev** [comment]
nah we can easily get get TS back in, but have the babel ts loader handle it

I was just lazy lol

**Review by conwaydev — APPROVED** [review]

**Comment by conwaydev** [comment]
but yeah my thinking was let webpack handle all the bundle/ tasks, hope thats chill

**Comment by conwaydev** [comment]
we should also talk API responses at some point my dude

**Comment by DarthHater** [comment]
Sounds good, I sorta preferred using Typescript because it cuts out a few of the annoying ES6 things in terms of exporting blah blah blah (I'm probably wrong).

I'll go ahead and merge this and we can just move it back to TS or whatever in another PR.

**Pull request merged**
